pipeline {
    agent any

    tools {
        maven 'Maven'
    }

    environment {
        DOCKER_HUB_USER = "9500588005"
    }

    stages {

        stage('Clone Code') {
            steps {
                git ' https://github.com/sowndharyasugu12-tech/proj2-jenkins-pipeline.git'
            }
        }

        stage('Build') {
            steps {
                dir('java-app') {
                sh 'mvn clean package'
                }
            }
        }

        stage('Unit Test') {
            steps {
                 dir('java-app') {
                sh 'mvn test'
                 }
            }
        }

        stage('SonarQube Analysis') {
            steps {
                script {
                    // Resolve SonarScanner tool path
                    def scannerHome = tool name: 'sonar-scanner', type: 'hudson.plugins.sonar.SonarRunnerInstallation'

                    // Run analysis with SonarQube environment
                    withSonarQubeEnv('MySonarQubeServer') {
                        sh "${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=proj2-jenkins-pipeline \
                            -Dsonar.sources=java-app/src \
                            -Dsonar.java.binaries=java-app/target/classes"
                    }
                }
            }
        }

  stage('Docker Build & Push') {
    steps {
        script {
            withDockerRegistry(credentialsId: 'dockerhub-credentials', url: '') {
                sh """
                    docker build \
                        -t  $DOCKER_HUB_USER/proj2-jenkins-pipeline:${env.BUILD_NUMBER} \
                        -t  $DOCKER_HUB_USER/proj2-jenkins-pipeline:latest \
                        java-app

                    docker push $DOCKER_HUB_USER/proj2-jenkins-pipeline:${env.BUILD_NUMBER}
                    docker push $DOCKER_HUB_USER/proj2-jenkins-pipeline:latest
                """
            }
        }
    }
}


       stage('Deploy to myproject2 Cluster') {
    steps {
        withCredentials([string(credentialsId: 'kubeconfig-myproject2', variable: 'KUBECONFIG_DATA')]) {
            sh '''
                echo "$KUBECONFIG_DATA" | base64 --decode > $WORKSPACE/kubeconfig
                export KUBECONFIG=$WORKSPACE/kubeconfig

                kubectl config use-context myproject2-context
                kubectl apply -f k8s/deployment.yaml
                kubectl apply -f k8s/service.yaml
            '''
        }
    }
}

        stage('Verify Deployment') {
            steps {
                sh 'kubectl get pods'
                sh 'kubectl get svc'
            }
        }
    }

    post {

        success {
            echo 'Pipeline Success'
        }

        failure {
            echo 'Pipeline Failed'
        }
    }
}
